// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyVuowIhFTX6rJ_l20K4nca8w6xXZrUqI',
    appId: '1:947534911897:web:19f272f6ee0f1f5a149b08',
    messagingSenderId: '947534911897',
    projectId: 'coderscombo-chatapp',
    authDomain: 'coderscombo-chatapp.firebaseapp.com',
    storageBucket: 'coderscombo-chatapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUT04ArNP5MkyllO43I3-txsZ2JqVBzmE',
    appId: '1:947534911897:android:e517b7f49199af11149b08',
    messagingSenderId: '947534911897',
    projectId: 'coderscombo-chatapp',
    storageBucket: 'coderscombo-chatapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3dvSCz10smZRBf21ZZaSpmdv4RWiVlgU',
    appId: '1:947534911897:ios:1d46f76e683102a5149b08',
    messagingSenderId: '947534911897',
    projectId: 'coderscombo-chatapp',
    storageBucket: 'coderscombo-chatapp.appspot.com',
    androidClientId: '947534911897-ci6vd8heu9th79jkt71qotu95i0quqh3.apps.googleusercontent.com',
    iosClientId: '947534911897-so6pmo8ilvp88r81t2dqa3583um2i0pn.apps.googleusercontent.com',
    iosBundleId: 'com.example.codersComboChatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3dvSCz10smZRBf21ZZaSpmdv4RWiVlgU',
    appId: '1:947534911897:ios:1d46f76e683102a5149b08',
    messagingSenderId: '947534911897',
    projectId: 'coderscombo-chatapp',
    storageBucket: 'coderscombo-chatapp.appspot.com',
    androidClientId: '947534911897-ci6vd8heu9th79jkt71qotu95i0quqh3.apps.googleusercontent.com',
    iosClientId: '947534911897-so6pmo8ilvp88r81t2dqa3583um2i0pn.apps.googleusercontent.com',
    iosBundleId: 'com.example.codersComboChatapp',
  );
}
